### ISSUE TITLE
FileNotfoundException

### ISSUE THREAD

**Issue by Fisherman91** [lijunhuayc/EasyFileDownloader#1]
下载目录设置为SD卡根目录或者根目录的某个子目录，就报这个异常，SD卡读写权限已加。
![Uploading 1.png…]()

**Comment by lijunhuayc** [comment]
为了较少库依赖和方法数，以及用户的权限使用方式，库中未提供动态权限申请。
Demo中已经新增动态权限申请，在执行开始下载前保证有Manifest.permission.WRITE_EXTERNAL_STORAGE权限即可。
